In [1]:
import numpy as np
print(np.__version__)
print("hello world")

2.0.2
hello world


In [4]:
x = 10
y = 3.14
name = "Felix"
is_student = True

print(type(x))
print(type(y))
print(type(name))
print(type(is_student))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [5]:
# arithmetic
print(10 + 3)
print(10 - 3)
print(10 * 3)
print(10 / 3)    # standard division
print(10 // 3)   # integer division
print(10 % 3)    # remainder
print(10 ** 3)   # power

# string operations
print("Felix" + " Neilson")   # concatenation
print("Felix" * 3)            # repetition

13
7
30
3.3333333333333335
3
1
1000
Felix Neilson
FelixFelixFelix


In [6]:
# lists are ordered, mutable, can mix types
numbers = [1, 2, 3, 4, 5]
mixed = [1, "hello", 3.14, True]

# indexing — zero based
print(numbers[0])    # first element
print(numbers[-1])   # last element
print(numbers[1:3])  # slice: index 1 up to (not including) 3

# modifying
numbers.append(6)       # add to end
numbers.insert(0, 0)    # insert at index 0
numbers.pop()           # remove last element
print(numbers)

# useful info
print(len(numbers))
print(sum(numbers))

1
5
[2, 3]
[0, 1, 2, 3, 4, 5]
6
15


In [7]:
# dictionaries are key-value pairs — you'll use these constantly
person = {
    "name": "Felix",
    "age": 23,
    "city": "Oxford"
}

# accessing
print(person["name"])
print(person.get("age"))        # safer way — returns None if key doesn't exist

# modifying
person["city"] = "London"       # update
person["job"] = "quant"         # add new key
del person["job"]               # delete

# iterating
for key, value in person.items():
    print(f"{key}: {value}")

# check if key exists
print("name" in person)

Felix
23
name: Felix
age: 23
city: London
True


In [8]:
# defining a function
def square(x):
    return x ** 2

def add(x, y):
    return x + y

# calling
print(square(5))
print(add(3, 4))

# default arguments
def greet(name, greeting="Hello"):
    return f"{greeting}, {name}!"

print(greet("Felix"))
print(greet("Felix", "Hey"))

# multiple return values
def min_max(lst):
    return min(lst), max(lst)

low, high = min_max([3, 1, 4, 1, 5, 9])
print(f"min: {low}, max: {high}")

25
7
Hello, Felix!
Hey, Felix!
min: 1, max: 9


In [9]:
# for loop over a list
numbers = [1, 2, 3, 4, 5]
for n in numbers:
    print(n ** 2)

# range
for i in range(5):        # 0, 1, 2, 3, 4
    print(i)

for i in range(2, 10, 2): # start, stop, step
    print(i)

# while loop
x = 0
while x < 5:
    print(x)
    x += 1

# enumerate — gives you index and value, use this instead of range(len(...))
fruits = ["apple", "banana", "cherry"]
for i, fruit in enumerate(fruits):
    print(f"{i}: {fruit}")

# list comprehension — very pythonic, learn to love it
squares = [x**2 for x in range(10)]
evens = [x for x in range(20) if x % 2 == 0]
print(squares)
print(evens)

1
4
9
16
25
0
1
2
3
4
2
4
6
8
0
1
2
3
4
0: apple
1: banana
2: cherry
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [11]:
def summarise(lst):
    dict_summary = {
        "mean": np.mean(lst),
        "min": np.min(lst),
        "max": np.max(lst),
        "range": np.ptp(lst),  # peak to peak (max - min)
        "length": len(lst)
    }
    return dict_summary

s = summarise([4, 7, 2, 9, 1, 5, 8, 3, 6])
for key, value in s.items():
    print(f"{key}: {value}")


mean: 5.0
min: 1
max: 9
range: 8
length: 9


In [12]:
# conditional logic
x = 15

if x > 20:
    print("big")
elif x > 10:
    print("medium")
else:
    print("small")

# one-liner version (ternary)
label = "big" if x > 20 else "small"
print(label)

# combining conditions
age = 23
has_degree = True

if age > 21 and has_degree:
    print("eligible")

if age < 18 or not has_degree:
    print("not eligible")

medium
small
eligible


In [13]:
import numpy as np

# creating arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array (matrix)

print(a)
print(b)
print(a.shape)   # (5,)
print(b.shape)   # (2, 3)
print(b.ndim)    # number of dimensions
print(b.dtype)   # data type

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
(5,)
(2, 3)
2
int64


In [14]:
# these are used constantly
print(np.zeros((3, 4)))       # 3x4 matrix of zeros
print(np.ones((2, 3)))        # 2x3 matrix of ones
print(np.eye(4))              # 4x4 identity matrix
print(np.arange(0, 10, 2))    # like range() but returns array
print(np.linspace(0, 1, 5))   # 5 evenly spaced points between 0 and 1

# random arrays — you'll use these a lot for testing
np.random.seed(42)            # for reproducibility
print(np.random.randn(3, 3))  # 3x3 standard normal
print(np.random.randint(0, 10, (3, 3)))  # 3x3 random integers 0-9

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
[[4 0 9]
 [5 8 0]
 [9 2 6]]


In [15]:
a = np.array([10, 20, 30, 40, 50])
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 1D indexing — same as lists
print(a[0])       # 10
print(a[-1])      # 50
print(a[1:4])     # [20 30 40]

# 2D indexing
print(B[0, 1])    # row 0, col 1 → 2
print(B[:, 1])    # all rows, col 1 → entire second column
print(B[1, :])    # row 1, all cols → entire second row
print(B[:2, 1:])  # first 2 rows, cols 1 onwards

# boolean indexing — very useful
print(a[a > 25])          # elements greater than 25
print(B[B % 2 == 0])      # all even elements

10
50
[20 30 40]
2
[2 5 8]
[4 5 6]
[[2 3]
 [5 6]]
[30 40 50]
[2 4 6 8]


In [16]:
a = np.array([1, 2, 3])
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# scalar operations apply elementwise
print(a * 2)
print(B * 2)
print(B ** 2)

# adding a 1D array to a 2D array — broadcasting
print(B + a)   # a gets broadcast across each row

# column-wise broadcasting
col = np.array([[1], [2], [3]])  # shape (3,1)
print(B + col)  # col gets broadcast across each column

[2 4 6]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [17]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# matrix multiplication
print(A @ B)          # preferred syntax
print(np.dot(A, B))   # same thing

# elementwise multiplication (not matrix mult)
print(A * B)

# transpose
print(A.T)

# linear algebra module
print(np.linalg.det(A))           # determinant
print(np.linalg.inv(A))           # inverse
print(np.linalg.norm(A))          # Frobenius norm by default

# eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

# solving linear system Ax = b
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print(x)
print(A @ x)   # should recover b

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
5.477225575051661
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[0.  0.5]
[1. 2.]


In [18]:
a = np.arange(12)
print(a)

# reshape
B = a.reshape(3, 4)   # 3x4 matrix
print(B)
print(B.reshape(2, 6))
print(B.reshape(-1))   # flatten back to 1D, -1 means "infer this dimension"
print(B.reshape(2, -1)) # 2 rows, infer columns

# stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack([a, b]))   # stack vertically → (2,3)
print(np.hstack([a, b]))   # stack horizontally → (6,)

A = np.ones((3, 2))
B = np.ones((3, 4))
print(np.hstack([A, B]))   # stack matrices horizontally → (3,6)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [19]:
def centre_and_scale(A):

    mean = np.mean(A, axis=0)  # mean of each column
    std = np.std(A, axis=0)    # std of each column
    return (A - mean) / std     # broadcasting will handle the subtraction/division

In [20]:
import time

# task: square every element in a large array

a = np.random.randn(1_000_000)

# slow way — Python loop
start = time.time()
result = [x**2 for x in a]
print(f"Python loop: {time.time() - start:.4f}s")

# fast way — numpy vectorised
start = time.time()
result = a ** 2
print(f"NumPy vectorised: {time.time() - start:.4f}s")

Python loop: 0.1132s
NumPy vectorised: 0.0120s


In [22]:
def pca_from_scratch(X, k):
    """
    Perform PCA on data matrix X and return the top k principal components.
    
    Parameters:
    X : numpy.ndarray
        The input data matrix of shape (n_samples, n_features).
    k : int
        The number of principal components to return.
        
    Returns:
    numpy.ndarray
        The top k principal components of shape (n_samples, k).
    """
    # Step 1: Centre the data
    X_centered = X - np.mean(X, axis=0)
    
    # Step 2: Compute the covariance matrix
    covariance_matrix = np.cov(X_centered, rowvar=False)
    
    # Step 3: Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)
    
    # Step 4: Sort eigenvalues and corresponding eigenvectors
    sorted_indices = np.argsort(eigenvalues)[::-1]
    sorted_eigenvectors = eigenvectors[:, sorted_indices]
    
    # Step 5: Select the top k eigenvectors
    top_k_eigenvectors = sorted_eigenvectors[:, :k]
    
    # Step 6: Project the data onto the top k eigenvectors
    X_pca = X_centered @ top_k_eigenvectors
    
    return X_pca

In [23]:
X = np.random.randn(100, 5)
print(pca_from_scratch(X, 2).shape)  # should print (100, 2)

(100, 2)
